# Generated by Django 3.2.20 on 2023-09-05 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_appuser_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('friendship_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('request_accepted', models.BooleanField()),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='first_user', to='chat.appuser')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='second_user', to='chat.appuser')),
            ],
        ),
    ]
