# Generated by Django 3.2.20 on 2023-09-06 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_friendship'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=256, unique=True)),
                ('image', models.FileField(upload_to='')),
                ('thumbnail', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
