# Generated by Django 3.2.20 on 2023-09-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_image_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='user',
            field=models.CharField(blank=True, db_index=True, max_length=256, null=True),
        ),
    ]
