# Generated by Django 3.2.20 on 2023-09-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='status',
            field=models.CharField(blank=True, max_length=1256, null=True),
        ),
    ]
